name: Refresh

on:
  push:
    branches:
      - main

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url  https://api.github.com/repos/jeanmichel25/resume/pages/builds \
            --header "Authorization: Bearer ${{ secrets.USER_TOKEN }}"
